import std/strutils
import std/nre

proc replaceSmiles*(content: string): string =
  let smiles = @[
  (":-):", """<img src="/images/smilies/ab.gif" alt=":-):">"""),
  (":hi_hi_hi:", """<img src="/images/smilies/ap.gif" alt=":hi_hi_hi:">"""),
  (":-(", """<img src="/images/smilies/ac.gif" alt=":-(">"""),
  (":ki_ss:", """<img src="/images/smilies/aj.gif" alt=":ki_ss:">"""),
  (":ny_tik:", """<img src="/images/smilies/bh.gif" alt=":ny_tik:">"""),
  ("::yaz-yk:", """<img src="/images/smilies/ae.gif" alt="::yaz-yk:">"""),
  (":-)", """<img src="/images/smilies/ag.gif" alt=":-)">"""),
  (":bra_vo:", """<img src="/images/smilies/bi.gif" alt=":bra_vo:">"""),
  (":nez-nayu:", """<img src="/images/smilies/bk.gif" alt=":nez-nayu:">"""),
  (":du_ma_et:", """<img src="/images/smilies/bw.gif" alt=":du_ma_et:">"""),
  (":sh_ok:", """<img src="/images/smilies/ai.gif" alt=":sh_ok:">"""),
  (";;-)))", """<img src="/images/smilies/bj.gif" alt=";;-)))">"""),
  (":a_g_a:", """<img src="/images/smilies/bs.gif" alt=":a_g_a:">"""),
  (":ne_vi_del:", """<img src="/images/smilies/bn.gif" alt=":ne_vi_del:">"""),
  (":smu:sche_nie:", """<img src="/images/smilies/ah.gif" alt=":smu:sche_nie:">"""),
  (":ni_zia:", """<img src="/images/smilies/bt.gif" alt=":ni_zia:">"""),
  (":ze_va_et:", """<img src="/images/smilies/au.gif" alt=":ze_va_et:">"""),
  (":men:", """<img src="/images/smilies/af.gif" alt=":men:">"""),
  (":mi_ga_et:", """<img src="/images/smilies/ad.gif" alt=":mi_ga_et:">"""),
  (":ya_hoo_oo:", """<img src="/images/smilies/bp.gif" alt=":ya_hoo_oo:">"""),
  (":ti_pa:", """<img src="/images/smilies/pleasantry.gif" alt=":ti_pa:">"""),
  (":dan_ser:", """<img src="/images/smilies/bo.gif" alt=":dan_ser:">"""),
  (":ne_ne_ne:", """<img src="/images/smilies/bl.gif" alt=":ne_ne_ne:">"""),
  (":za_da_va_la:", """<img src="/images/smilies/ao.gif" alt=":za_da_va_la:">"""),
  (":-ok-:", """<img src="/images/smilies/bf.gif" alt=":-ok-:">"""),
  (":co_ol:", """<img src="/images/smilies/ay.gif" alt=":co_ol:">"""),
  (":cry_ing:", """<img src="/images/smilies/ak.gif" alt=":cry_ing:">"""),
  (":ps_ih:", """<img src="/images/smilies/bm.gif" alt=":ps_ih:">"""),
  (":)-(:", """<img src="/images/smilies/tease.gif" alt=":)-(:">"""),
  (":k_i_n_g:", """<img src="/images/smilies/king2.gif" alt=":k_i_n_g:">"""),
  (":lo)(ve:", """<img src="/images/smilies/first_move.gif" alt=":lo)(ve:">"""),
  (":ki_ng:", """<img src="/images/smilies/king.gif" alt=":ki_ng:">"""),
  (":jn_pu_sk:", """<img src="/images/smilies/smoke.gif" alt=":jn_pu_sk:">"""),
  (":ry_car:", """<img src="/images/smilies/paladin.gif" alt=":ry_car:">"""),
  (":p_a-r_t_y:", """<img src="/images/smilies/party.gif" alt=":p_a-r_t_y:">"""),
  (":ved_ma:", """<img src="/images/smilies/girl_werewolf.gif" alt=":ved_ma:">"""),
  (":zvez_ochki:", """<img src="/images/smilies/ck.gif" alt=":zvez_ochki:">"""),
  (":ts_ss:", """<img src="/images/smilies/al.gif" alt=":ts_ss:">"""),
  (":ig_ro_ki:", """<img src="/images/smilies/Laie_73.gif" alt=":ig_ro_ki:">"""),
  (":cool_cool:", """<img src="/images/smilies/cool2.gif" alt=":cool_cool:">"""),
  (":st_ruskiy:", """<img src="/images/smilies/russian_ru.gif" alt=":st_ruskiy:">"""),
  (":ro_za:", """<img src="/images/smilies/ax.gif" alt=":ro_za:">"""),
  (":ras_pal_cov_ka:", """<img src="/images/smilies/bd.gif" alt=":ras_pal_cov_ka:">"""),
  (":pi_rat:", """<img src="/images/smilies/pir.gif" alt=":pi_rat:">"""),
  (":du_el:", """<img src="/images/smilies/duel.gif" alt=":du_el:">"""),
  (":al_kana_ft:", """<img src="/images/smilies/russian.gif" alt=":al_kana_ft:">"""),
  (":-|-:", """<img src="/images/smilies/bq.gif" alt=":-|-:">"""),
  (":ki-)(-:", """<img src="/images/smilies/as.gif" alt=":ki-)(-:">"""),
  (":dr_ink:", """<img src="/images/smilies/az.gif" alt=":dr_ink:">"""),
  (":st_op:", """<img src="/images/smilies/av.gif" alt=":st_op:">"""),
  (":de_vil:", """<img src="/images/smilies/aq.gif" alt=":de_vil:">"""),
  (":obdol_bysh:", """<img src="/images/smilies/hang2.gif" alt=":obdol_bysh:">"""),
  (":mu_zyk:", """<img src="/images/smilies/ar.gif" alt=":mu_zyk:">"""),
  (":ar_ti_st:", """<img src="/images/smilies/scenic.gif" alt=":ar_ti_st:">"""),
  (":ta-ne-c:", """<img src="/images/smilies/dance.gif" alt=":ta-ne-c:">"""),
  (":kli_ny:", """<img src="/images/smilies/be.gif" alt=":kli_ny:">"""),
  (":ex_po_bo_ku:", """<img src="/images/smilies/likeff_man.gif" alt=":ex_po_bo_ku:">"""),
  (":gim-nast:", """<img src="/images/smilies/he.gif" alt=":gim-nast:">"""),
  (":aiki-do:", """<img src="/images/smilies/aikido.gif" alt=":aiki-do:">"""),
  (":e-d-a:", """<img src="/images/smilies/eat2.gif" alt=":e-d-a:">"""),
  (":tema-close:", """<img src="/images/smilies/close_tema.gif" alt=":tema-close:">"""),
  (":gir_l-fri_end:", """<img src="/images/smilies/aw.gif" alt=":gir_l-fri_end:">"""),
  (":fe_me_ly:", """<img src="/images/smilies/JC_parents-girl.gif" alt=":fe_me_ly:">"""),
  (";wont_a_ban:", """<img src="/images/smilies/KidRock_01.gif" alt=";wont_a_ban:">"""),
  (":ad_min_v_duhe:", """<img src="/images/smilies/KidRock_07.gif" alt=":ad_min_v_duhe:">"""),
  (":po_zor:", """<img src="/images/smilies/poz.gif" alt=":po_zor:">"""),
  (":an_gel:", """<img src="/images/smilies/angel.gif" alt=":an_gel:">"""),
  (":se_lya_ne:", """<img src="/images/smilies/boyan.gif" alt=":se_lya_ne:">"""),
  (":goria_cho:", """<img src="/images/smilies/heat.gif" alt=":goria_cho:">"""),
  (":is_te_ri_ka:", """<img src="/images/smilies/girl_cray2.gif" alt=":is_te_ri_ka:">"""),
  (":du-ra:", """<img src="/images/smilies/girl_wacko.gif" alt=":du-ra:">"""),
  (":wo)(ll:", """<img src="/images/smilies/dash3.gif" alt=":wo)(ll:">"""),
  (":spi_der:", """<img src="/images/smilies/ext_spid.gif" alt=":spi_der:">"""),
  (":v_i_k_i_n_g:", """<img src="/images/smilies/dwarf.gif" alt=":v_i_k_i_n_g:">"""),
  (":mo-ro_zi_vo:", """<img src="/images/smilies/d_ice.gif" alt=":mo-ro_zi_vo:">"""),
  (":ga-ze-ta;", """<img src="/images/smilies/read.gif" alt=":ga-ze-ta;">"""),
  (":nel-zya:", """<img src="/images/smilies/nono.gif" alt=":nel-zya:">"""),
  (":an)(gel:", """<img src="/images/smilies/JC_cupidboy.gif" alt=":an)(gel:">"""),
  (":son-ce:", """<img src="/images/smilies/hy.gif" alt=":son-ce:">"""),
  (":pa_la_ch:", """<img src="/images/smilies/butcher.gif" alt=":pa_la_ch:">"""),
  (":za_gar:", """<img src="/images/smilies/beach.gif" alt=":za_gar:">"""),
  (":ho-key:", """<img src="/images/smilies/nhl.gif" alt=":ho-key:">"""),
  (":pri_vet:-:", """<img src="/images/smilies/br.gif" alt=":pri_vet:-:">"""),
  (":uch_tiv:", """<img src="/images/smilies/hi.gif" alt=":uch_tiv:">"""),
  (":lo_ve:", """<img src="/images/smilies/give_heart.gif" alt=":lo_ve:">"""),
  (":sh_ut:", """<img src="/images/smilies/jester.gif" alt=":sh_ut:">"""),
  (":dra_chun:", """<img src="/images/smilies/am.gif" alt=":dra_chun:">"""),
  (":pisa_tel:", """<img src="/images/smilies/bv.gif" alt=":pisa_tel:">"""),
  (":igru_shka:", """<img src="/images/smilies/to_become_senile.gif" alt=":igru_shka:">"""),
  (":wo_rk:", """<img src="/images/smilies/moil.gif" alt=":wo_rk:">"""),
  (":danser_dans:", """<img src="/images/smilies/dance4.gif" alt=":danser_dans:">"""),
  (":ole_ole:", """<img src="/images/smilies/fans.gif" alt=":ole_ole:">"""),
  (":ot_riad:", """<img src="/images/smilies/pioneerrr.gif" alt=":ot_riad:">"""),
  (":te_le_fon:", """<img src="/images/smilies/telephone.gif" alt=":te_le_fon:">"""),
  (":poz_drav_liayu:", """<img src="/images/smilies/shar.gif" alt=":poz_drav_liayu:">"""),
  (":ya-za:", """<img src="/images/smilies/ex.gif" alt=":ya-za:">"""),
  (":ne_ne_ne:", """<img src="/images/smilies/fie.gif" alt=":ne_ne_ne:">"""),
  (":exp_minus:", """<img src="/images/smilies/likeopera_man.gif" alt=":exp_minus:">"""),
  (":ups:", """<img src="/images/smilies/oops.gif" alt=":ups:">"""),
  (":hudo_zhnik:", """<img src="/images/smilies/ho.gif" alt=":hudo_zhnik:">"""),
  (":-:ok:-:", """<img src="/images/smilies/cool.gif" alt=":-:ok:-:">"""),
  (":;ne_gr:", """<img src="/images/smilies/bg.gif" alt=":;ne_gr:">"""),
  (":kav_boy:", """<img src="/images/smilies/Laie_34.gif" alt=":kav_boy:">"""),
  (":bo_ga_tyr:", """<img src="/images/smilies/orc.gif" alt=":bo_ga_tyr:">"""),
  (":hea_rt:", """<img src="/images/smilies/ba.gif" alt=":hea_rt:">"""),
  (":bet_ment:", """<img src="/images/smilies/neo.gif" alt=":bet_ment:">"""),
  (":na_met_le:", """<img src="/images/smilies/girl_witch.gif" alt=":na_met_le:">"""),
  (":ko_pi_lka:", """<img src="/images/smilies/Laie_11.gif" alt=":ko_pi_lka:">"""),
  (":pioner:", """<img src="/images/smilies/pioneer.gif" alt=":pioner:">"""),
  (":ohot_nik:", """<img src="/images/smilies/hunter.gif" alt=":ohot_nik:">"""),
  (":bomb:", """<img src="/images/smilies/bb.gif" alt=":bomb:">"""),
  (":fo_tik:", """<img src="/images/smilies/d_canon.gif" alt=":fo_tik:">"""),
  (":pro_spal:", """<img src="/images/smilies/ha.gif" alt=":pro_spal:">"""),
  (":wo_ol:", """<img src="/images/smilies/bu.gif" alt=":wo_ol:">"""),
  (":pro_tiv:", """<img src="/images/smilies/ew.gif" alt=":pro_tiv:">"""),
  (":f-l-u-d:", """<img src="/images/smilies/KidRock_03.gif" alt=":f-l-u-d:">"""),
  (";tor_moz:", """<img src="/images/smilies/slow.gif" alt=";tor_moz:">"""),
  (":dev_ka:", """<img src="/images/smilies/brunette.gif" alt=":dev_ka:">"""),
  (":ba_bo_ch_ka:", """<img src="/images/smilies/kiss.gif" alt=":ba_bo_ch_ka:">"""),
  (":sk_ri_pa_ch:", """<img src="/images/smilies/fu.gif" alt=":sk_ri_pa_ch:">"""),
  (":med_ses_tra:", """<img src="/images/smilies/girl_hospital.gif" alt=":med_ses_tra:">"""),
  (":ne_ot_ho_di:", """<img src="/images/smilies/KidRock_05.gif" alt=":ne_ot_ho_di:">"""),
  (":ko_re:sha:", """<img src="/images/smilies/friends.gif" alt=":ko_re:sha:">"""),
  (":s_o_s:", """<img src="/images/smilies/bc.gif" alt=":s_o_s:">"""),
  (":ta_n_cor:", """<img src="/images/smilies/dance3.gif" alt=":ta_n_cor:">"""),
  (":gar_mo:nist:", """<img src="/images/smilies/fx.gif" alt=":gar_mo:nist:">"""),
  (":ze_le_ny:", """<img src="/images/smilies/at.gif" alt=":ze_le_ny:">"""),
  (":hu_li:gan:", """<img src="/images/smilies/connieslingshotxt0.gif" alt=":hu_li:gan:">"""),
  (":ded_moroz:", """<img src="/images/smilies/fc.gif" alt=":ded_moroz:">"""),
  (":pi_ra_t:", """<img src="/images/smilies/drag_06.gif" alt=":pi_ra_t:">"""),
  (":fe_mi_ni_zm;", """<img src="/images/smilies/feminist.gif" alt=":fe_mi_ni_zm;">"""),
  (":te_ma-clo_se:", """<img src="/images/smilies/KidRock_06.gif" alt=":te_ma-clo_se:">"""),
  (":windows_must_die:", """<img src="/images/smilies/snoozer_likelinux_man.gif" alt=":windows_must_die:">"""),
  (":foo_t_bol:", """<img src="/images/smilies/football.gif" alt=":foo_t_bol:">"""),
  (":chir_lider:", """<img src="/images/smilies/Mauridia_21.gif" alt=":chir_lider:">"""),
  (":ku_bok:", """<img src="/images/smilies/st.gif" alt=":ku_bok:">"""),
  (":cve_ty:", """<img src="/images/smilies/dw.gif" alt=":cve_ty:">""")]

  var pre = strutils.multiReplace(content, smiles)
  
  pre = pre
    .replace(
    re"htt(p|ps):\/\/[\w.]+youtube\.[\w]+\/watch[(\?|\?feature=player_embedded&amp;)\\#!]+v=([\w-]+)[\w&;+-]*[\#&;t=]*([\d]*)[&;10wshdq=]*",
    "<div class=\"video-responsive\"><iframe width=\"640\" height=\"360\" src=\"//www.youtube.com/embed/$2?fs=1&start=$3\" frameborder=\"0\" allowfullscreen=\"true\"></iframe></div>")
    .replace(
    re"htt(p|ps):\/\/[w\.]*youtu\.be\/([-a-zA-Z0-9&;+=_]*)[\w;+=-]*[\#\?&t=]*([\d]*)[&;10wshdq=]*",
    "<div class=\"video-responsive\"><iframe width=\"640\" height=\"360\" src=\"//www.youtube.com/embed/$2?fs=1&start=$3\" frameborder=\"0\" allowFullScreen=\"true\"></iframe></div>")
    .replace(
    re"htt(p|ps):\/\/[w\.]*vimeo\.com\/([\d]+)[\w&;=\?+%\/-]*",
    "<div class=\"video-responsive\"><iframe src=\"//player.vimeo.com/video/$2\" width=\"640\" height=\"360\" frameborder=\"0\" allowfullscreen=\"true\"></iframe></div>")
    .replace(
    re"htt(p|ps):\/\/rutube.ru\/video\/([-a-zA-Z0-9&;+=_]*)",
    "<div class=\"video-responsive\"><iframe width=\"640\" height=\"360\" allowfullscreen=\"\" scrolling=\"no\" src=\"//rutube.ru/play/embed/$2\"></iframe></div>")
    .replace(
    re"htt(p|ps):\/\/(?:[^.\/]+\.)*t\.me\/(\w+\/\d+)",
    "<iframe frameborder=\"0\" data-s9e-mediaembed=\"telegram\" allowfullscreen=\"\" onload=\"var c=new MessageChannel;c.port1.onmessage=function(e){style.height=e.data+'px'};contentWindow.postMessage('s9e:init','https://s9e.github.io',[c.port2])\" scrolling=\"no\" style=\"height:96px;width:500px\" data-s9e-mediaembed-api=\"2\" src=\"https://s9e.github.io/iframe/2/telegram.min.html#$2\"></iframe>")
    .replace(
    re"htt(p|ps):\/\/twitter\.com\/(?:#!\/|i\/)?\w+\/(?:status(?:es)?|tweet)\/(\d+)(?:\?\S+)?",
    "<iframe frameborder=\"0\" data-s9e-mediaembed=\"twitter\" allow=\"autoplay *\" allowfullscreen=\"\" onload=\"var c=new MessageChannel;c.port1.onmessage=function(e){style.height=e.data+'px'};contentWindow.postMessage('s9e:init','https://s9e.github.io',[c.port2])\" scrolling=\"no\" style=\"height:273px;width:550px\" data-s9e-mediaembed-api=\"2\" src=\"https://s9e.github.io/iframe/2/twitter.min.html#$2\"></iframe>")
  
  result = pre.strip()
